### ISSUE TITLE
D2 Task-017: Rectificación modelo UML con los cambios propuestos

### ISSUE THREAD

**Issue by ddiazlop** [mansanrod4/Acme-Toolkits#73]
Mirar las diapositivas para normalizar el formato del uml.

**Comment by mansanrod4** [comment]
- [ ] AdministratorDashboard
- [ ] /secuenceNumber de PatronageReport
- [ ] Revisar Date: {Temporal(TIMESTAMP), Past}
- [ ] Revisar estereotipos de entidades
- [ ] Borrar las que vienen del framework
- [ ] Relación Inventor - Item & Inventor - Toolkit
